### ISSUE TITLE
Change the Description of Repo

### ISSUE THREAD

**Issue by Dark1z** [marttiphpbb/phpbb-ext-showphpbbevents#1]
Change the Description of Repo,   
From : phpBB extension which shows all phpBB core events (for extension developers)    
To : phpBB extension which shows all phpBB core `& template` events (for extension developers)   

Best regards. 👍

**Comment by marttiphpbb** [comment]
Well, the extension shows only core events. It doesn't show events (PHP & template) from extensions. It might be misleading because all PHP events are prefixed with `core`.  
Maybe better:
"phpBB extension which shows all phpBB core PHP and template events (for extension developers). "

**Comment by Dark1z** [comment]
> Well, the extension shows only core events. It doesn't show events (PHP & template) from extensions. It might be misleading because all PHP events are prefixed with core.
Maybe better:
"phpBB extension which shows all phpBB core PHP and template events (for extension developers). "    


No problem as long as it is understood that it has PHP & Template events in this extension.

BR 👍
