### ISSUE TITLE
Update events, question.

### ISSUE THREAD

**Issue by 3D-I** [marttiphpbb/phpbb-ext-showphpbbevents#5]
Does this extension automatically recognise the new events (say phpBB 3.3.7)?

If not, any chance to have it updated please? Thanks.

**Comment by eeemarv** [comment]
It doesn't go automatically, unfortunately. But the extension is now updated to include all the events up to phpBB 3.3.7  ( 8fa7fd8b )

**Comment by 3D-I** [comment]
Thanks m8, much appreciated. It saves me a lot of time. 💯
